export type Lang = 'en' | 'ka';

/** Ingredient units as the Georgian list shows them; anything not listed is shown as written. */
export const UNITS_KA: Record<string, string> = {
  g: 'გ',
  kg: 'კგ',
  ml: 'მლ',
  l: 'ლ',
  tsp: 'ჩ.კ.',
  tbsp: 'ს.კ.',
  cm: 'სმ',
  clove: 'კბილი',
  cloves: 'კბილი',
  slice: 'ნაჭერი',
  slices: 'ნაჭერი',
  pinch: 'მწიკვი',
  handful: 'ერთი მუჭა',
  jar: 'ქილა',
  spoonful: 'ერთი კოვზი',
  drizzle: 'ცოტა',
  'a little': 'ცოტა',
  'to cover': 'დასაფარად',
  'to taste': 'გემოვნებით',
  'to serve': 'მისატანებლად',
};

export const LEVELS_KA: Record<string, string> = {
  Easy: 'მარტივი',
  Medium: 'საშუალო',
  Hard: 'რთული',
};

const EN = {
  skipToContent: 'Skip to content',
  navHome: 'Home',
  navBrowse: 'Browse',
  navSaved: 'Saved',
  searchRecipes: 'Search recipes',
  saveRecipe: 'Save this recipe',
  unsaveRecipe: 'Remove from saved recipes',
  savedRecipes: 'Saved recipes',
  /** The switch shows the language it leads to. */
  switchLabel: 'ქარ',
  switchAria: 'ქართულად',
  footerTagline: 'Recipes rescued from bookmarks, screenshots and group chats. Cooked, then kept.',
  footerPhoto: 'Photography via Unsplash.',
  thisWeek: 'This week',
  minutes: (n: number) => `${n} min`,
  serves: (n: number) => `Serves ${n}`,
  perHead: (cost: string) => `${cost} a head`,
  seeRecipe: 'See the recipe',
  browseByMeal: 'Browse by meal',
  swipe: 'Swipe',
  recipeCount: (n: number) => `${n} ${n === 1 ? 'recipe' : 'recipes'}`,
  newThisWeek: 'New this week',
  newBlurb: 'Six things worth cooking before Sunday.',
  kidsTitle: 'Dinners that end without a negotiation',
  kidsCount: (n: number) => `${n} ${n === 1 ? 'recipe' : 'recipes'} tested on people under ten.`,
  seeCollection: 'See the collection',
  allRecipes: 'All recipes',
  countOf: (shown: number, total: number) => `${shown} of ${total} recipes`,
  searchPlaceholder: 'Search by name or ingredient',
  nothingMatchesQuery: (q: string) => `Nothing matches “${q}” yet.`,
  otherCategories: 'Other categories',
  previousCategory: (name: string) => `Previous category: ${name}`,
  nextCategory: (name: string) => `Next category: ${name}`,
  noSuchCategory: 'No such category',
  notFoundHint: 'Try one of the meals on the ',
  browsePage: 'browse page',
  filterRecipes: 'Filter recipes',
  all: 'All',
  under30: 'Under 30 min',
  nothingMatchesFilter: 'Nothing matches that filter yet.',
  adaptedFrom: 'Adapted from',
  save: 'Save',
  saved: 'Saved',
  watchVideo: 'Watch video',
  opensNewTab: '(opens in a new tab)',
  startCookMode: 'Start cook mode',
  ingredients: 'Ingredients',
  method: 'Method',
  servingsLabel: 'Servings',
  servingCount: (n: number) => `${n} ${n === 1 ? 'serving' : 'servings'}`,
  fewerServings: 'Fewer servings',
  moreServings: 'More servings',
  recipeNotFound: 'Recipe not found',
  mayBeRenamed: 'It may have been renamed.',
  browseAll: 'Browse all recipes',
  cookMode: 'Cook mode',
  closeCookMode: 'Close cook mode',
  stepOf: (i: number, n: number) => `Step ${i} of ${n}`,
  previousStep: 'Previous step',
  done: 'Done',
  nextStep: 'Next step',
  savedTitle: 'Saved',
  nothingSaved:
    'Nothing saved yet. Tap the bookmark on any recipe and it will wait for you here, on this device.',
  siteTitle: 'Recipio · recipes worth cooking again',
  allRecipesTitle: 'All recipes · Recipio',
  savedRecipesTitle: 'Saved recipes · Recipio',
  categoryTitle: (name: string) => `${name} recipes · Recipio`,
  categoryNotFound: 'Category not found',
};

const KA: typeof EN = {
  skipToContent: 'შიგთავსზე გადასვლა',
  navHome: 'მთავარი',
  navBrowse: 'რეცეპტები',
  navSaved: 'შენახული',
  searchRecipes: 'რეცეპტების ძებნა',
  saveRecipe: 'რეცეპტის შენახვა',
  unsaveRecipe: 'შენახულებიდან წაშლა',
  savedRecipes: 'შენახული რეცეპტები',
  switchLabel: 'ENG',
  switchAria: 'Switch to English',
  footerTagline:
    'სანიშნეებიდან, სქრინშოტებიდან და ჩატებიდან გადარჩენილი რეცეპტები. მოვამზადეთ და შევინახეთ.',
  footerPhoto: 'ფოტოები: Unsplash.',
  thisWeek: 'ამ კვირას',
  minutes: (n) => `${n} წთ`,
  serves: (n) => `${n} პორცია`,
  perHead: (cost) => `${cost} ერთ ადამიანზე`,
  seeRecipe: 'რეცეპტის ნახვა',
  browseByMeal: 'კერძის მიხედვით',
  swipe: 'გადაფურცლე',
  recipeCount: (n) => `${n} რეცეპტი`,
  newThisWeek: 'ახალი ამ კვირას',
  newBlurb: 'ექვსი კერძი, რომელიც კვირამდე ღირს მოამზადო.',
  kidsTitle: 'ვახშმები, რომლებიც მოლაპარაკების გარეშე მთავრდება',
  kidsCount: (n) => `${n} რეცეპტი, გამოცდილი ათ წლამდე ასაკის ხალხზე.`,
  seeCollection: 'კოლექციის ნახვა',
  allRecipes: 'ყველა რეცეპტი',
  countOf: (shown, total) => `${total}-დან ${shown} რეცეპტი`,
  searchPlaceholder: 'ძებნა სახელით ან ინგრედიენტით',
  nothingMatchesQuery: (q) => `„${q}“ ჯერ არაფერს ემთხვევა.`,
  otherCategories: 'სხვა კატეგორიები',
  previousCategory: (name) => `წინა კატეგორია: ${name}`,
  nextCategory: (name) => `შემდეგი კატეგორია: ${name}`,
  noSuchCategory: 'ასეთი კატეგორია არ არსებობს',
  notFoundHint: 'აირჩიე კატეგორია ',
  browsePage: 'რეცეპტების გვერდზე',
  filterRecipes: 'რეცეპტების ფილტრი',
  all: 'ყველა',
  under30: '30 წუთამდე',
  nothingMatchesFilter: 'ამ ფილტრით ჯერ არაფერია.',
  adaptedFrom: 'წყარო:',
  save: 'შენახვა',
  saved: 'შენახულია',
  watchVideo: 'ვიდეოს ნახვა',
  opensNewTab: '(იხსნება ახალ ჩანართში)',
  startCookMode: 'მზადების რეჟიმი',
  ingredients: 'ინგრედიენტები',
  method: 'მომზადება',
  servingsLabel: 'პორციები',
  servingCount: (n) => `${n} პორცია`,
  fewerServings: 'ნაკლები პორცია',
  moreServings: 'მეტი პორცია',
  recipeNotFound: 'რეცეპტი ვერ მოიძებნა',
  mayBeRenamed: 'შესაძლოა სახელი შეეცვალა.',
  browseAll: 'ყველა რეცეპტის ნახვა',
  cookMode: 'მზადების რეჟიმი',
  closeCookMode: 'რეჟიმის დახურვა',
  stepOf: (i, n) => `ნაბიჯი ${i} / ${n}`,
  previousStep: 'წინა ნაბიჯი',
  done: 'მზადაა',
  nextStep: 'შემდეგი ნაბიჯი',
  savedTitle: 'შენახული',
  nothingSaved:
    'ჯერ არაფერია შენახული. დააჭირე სანიშნეს ნებისმიერ რეცეპტზე და ის აქ დაგელოდება, ამ მოწყობილობაზე.',
  siteTitle: 'Recipio · რეცეპტები, რომლებსაც ისევ მოამზადებ',
  allRecipesTitle: 'ყველა რეცეპტი · Recipio',
  savedRecipesTitle: 'შენახული რეცეპტები · Recipio',
  categoryTitle: (name) => `${name} · Recipio`,
  categoryNotFound: 'კატეგორია ვერ მოიძებნა',
};

export const UI: Record<Lang, typeof EN> = { en: EN, ka: KA };
export type UiKey = keyof typeof EN;
